name: C++/C CMake (Debug build with Visual Studio MSVC)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.275.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Configure CMake (Visual Studio + MSVC)
      run: cmake -S "${{ github.workspace }}/Ifnity" -B "${{ github.workspace }}/out/build/Ifnity-Debug" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug

    - name: Build with MSVC
      run: cmake --build "${{ github.workspace }}/out/build/Ifnity-Debug" --config Debug
