name: C++/C CMake (Debug build with Visual Studio MSVC)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.275.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Configure CMake (Visual Studio 2022, x64)
      run: |
        cmake -S ${{github.workspace}}/Ifnity `
              -B ${{github.workspace}}/Ifnity/build `
              -G "Visual Studio 17 2022" `
              -A x64

    - name: Build (Debug)
      run: |
        cmake --build ${{github.workspace}}/Ifnity/build --config Debug

    - name: Test (Optional)
      if: success()
      run: |
        ctest --test-dir ${{github.workspace}}/Ifnity/build --build-config Debug --output-on-failure
