name: C++/C CMake (Debug build with Visual Studio MSVC)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Ensure submodules are updated recursively
      run: |
        git submodule sync --recursive
        git submodule update --init --recur
